[meta]
name = "The Badlands"

[locales]

    [locales.forest]
    name = "Forest"
    description = "Sunlight falls through the leaves."
        [locales.forest.dirs]
        north = "Deep Forest"
        south = "Spooky House"

    [locales.house]
    name = "Spooky House"
    description = "The floors creek!"
        [locales.house.dirs]
        north = "Forest"

    [locales.deepforest]
    name = "Deep Forest"
    description = "The here is very dense."
        [locales.deepforest.dirs]
        south = "Forest"
        west = "Crater"

    [locales.crater]
    name = "Crater"
    description = "You can't see the bottom of it."
        [locales.crater.dirs]
        east = "Deep Forest"
